apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: cta
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/cta"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "admin"
  JWT_SECRET: "my-secret-key-minimum-32-characters-long"
  JWT_EXPIRATION: "86400000"
  ENVIRONMENT: "kubernetes"